### ISSUE TITLE
The log file says that LIP added VBA module even though it didn't

### ISSUE THREAD

**Issue by justFredster** [Lundalogik/lip#34]
Example from the log file:

Adding VBA modules, forms and classes...
  Module "ActionPad_Company" already exists and have not been replaced.
  Added ActionPad_Company

The "Added..." row should not be written to the log if the module was not added/replaced.

**Comment by LarsCJensen** [comment]
I suspect that it is lip.installVBAComponents that is the villain. In addModule method it has logic to write "Added X" but the calling function always writes "Added X" even though you didn't replace a component. If the module doesn't exist in the package it does not set addModule to False, thus writing "Added X" anyway.

**Comment by justFredster** [comment]
Fixed by @LarsCJensen  in #39.
