### ISSUE TITLE
Installing the FormProgress form gives an error

### ISSUE THREAD

**Issue by justFredster** [Lundalogik/lip#40]
Errors shown in the pictures below:

![30743498_365177000659923_1562632862684955776_n](https://user-images.githubusercontent.com/5981735/39292983-ffc3360a-4937-11e8-844e-442b085cc7fd.jpg)

![30706100_365177760659847_5214685438113107949_n](https://user-images.githubusercontent.com/5981735/39292991-09b4499c-4938-11e8-8666-dc0d45c01fae.jpg)

**Comment by LarsCJensen** [comment]
Would you say this is a LIP issue? It has to do with the progress control itself, as well as other controls I would suspect (missing some ocx/dll on the machine).
Have you seen this before, by the way? I've seen something like this with tree view and img control, but don't remember if I solved it.

**Comment by justFredster** [comment]
Talked to Lars about it: We can do something in the LIP code to only use the progressbar form if it exists. We added a Trello card for it.

**Comment by LarsCJensen** [comment]
The quickest way around is to install LIP from another computer. I think the crook is comctl32.ocx but I haven't been able to confirm it since a restart of the computer (server in my cases) have not been possible. After LIP has been installed from another computer it has been working on the server, so I think some kind of reference have been added in the process.

**Comment by jonnyspringare** [comment]
I have seen a case where we installed LIP from another computer. However, when we logged in at the server again (from which we couldn't install LIP) we received a VBA error just by logging in to Lime.

I have created a new basic progressbar which I hope can solve the problem, but needs to be tested first.

**Comment by justFredster** [comment]
Probably solved in #42. Needs to be tested in an environment where the error occurred. @jonnyspringare will do this.

**Comment by LarsCJensen** [comment]
@jonnyspringare This is fixed, is it not?

**Comment by jonnyspringare** [comment]
> @jonnyspringare This is fixed, is it not?

Yes, it is (included now in master and has been tested and verified in an environment that had the problem)
