### ISSUE TITLE
Lip does not handle the apostrophe(') character

### ISSUE THREAD

**Issue by amanomio** [Lundalogik/lip#41]
"localname": {
              "sv": "Att g\u00F6ra",
		"no": "Oppgave",
		"fi": "Teht\u00E4v\u00E4t",
		"en_us": "To-do's",
		"da": "Opgaver"
}

**Comment by LarsCJensen** [comment]
Hmm, I'm pretty sure we have addressed this issue. Is this an error in LIP or in the PackageBuilder?

**Comment by SimonJehrbo** [comment]
I'm having the issue with french translations. The package gets created with packageBuilder but fails when installing.
"fr":"Chiffre d'affaires du mois dernier de l'ann\u00E9e derni\u00E8re"

**Comment by justFredster** [comment]
Was it the latest version of LIP?

**Comment by LarsCJensen** [comment]
@justFredster I don't think we've fixed this yet

**Comment by LarsCJensen** [comment]
As I stated, it hasn't been fixed. I can see if we can get it fixed during next week.

**Comment by LarsCJensen** [comment]
@SimonJehrbo Could you use the csp_lip_setfieldattribute from master branch to see if that solves your issue? If it does I will use the same fix for other similar issues.

**Comment by SimonJehrbo** [comment]
@LarsCJensen works like a charm!

**Comment by LarsCJensen** [comment]
I've made the same change for how table names are handled.
